name: 'Natron Conan Setup Action'
description: 'Common steps for setting up Conan for Natron builds'
inputs:
  conan_profile:
    description: 'Profile used tor building'
    required: true

  restore_cache_filename:
    description: 'Filename used to restore conan cache'
    required: false
    default: ""

runs:
  using: "composite"
  steps:
      - name: Install Linux system packages
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt update
          sudo apt install build-essential cmake extra-cmake-modules libgl-dev \
            libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev \
            libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev \
            libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev \
            libxxf86vm-dev libxcb-glx0-dev libxcb-render-util0-dev libxcb-xkb-dev \
            libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev \
            libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev \
            libxcb-dri3-dev libxcb-cursor-dev libxcb-dri2-0-dev libxcb-dri3-dev \
            libxcb-present-dev libxcb-composite0-dev libxcb-ewmh-dev libxcb-res0-dev \
            libxcb-util-dev libxcb-util0-dev libxkbfile-dev uuid-dev \
            libegl-dev

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - name: Install Pip requirements
        shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
        run: |
          pip install -r .github/workflows/requirements.txt

      - name: Install conan config
        shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
        run: |
          conan config install -t dir config

      - name: Download Minimal Windows packages from conan-center-index
        if: runner.os == 'Windows'
        shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
        run: |
          conan download -r conancenter "msys2/cci.latest"

      - name: Download Minimal Linux packages from conan-center-index
        if: runner.os == 'Linux' || runner.os == 'macOS'
        shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
        run: |
          conan download -r conancenter "gnu-config/cci.20210814"

      - name: Restore conan cache
        if: inputs.restore_cache_filename != ''
        shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
        run: |
          curl -L -o ${{ inputs.restore_cache_filename }} https://github.com/acolwell/natron_conan_env/releases/download/conan_cache/${{ inputs.restore_cache_filename }}
          conan cache restore ${{ inputs.restore_cache_filename }}
          rm ${{ inputs.restore_cache_filename }}

      - name: Add Natron specific Conan remotes
        shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
        run: |
          conan remote remove conancenter
          conan remote add natron_recipes ${{ github.workspace }}
          conan remote add natron_conancenter ${{ github.workspace }}/modules/conan-center-index
