name: Build Conan Caches

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'scripts/getBuildConanCachesPackageInfo.py'
      - 'scripts/natron_conan_env.py'
      - '.github/workflows/build_conan_caches.yml'
      - 'recipes/natron/all/conanfile.py'
      - 'modules/conan-center-index'

  pull_request:
    paths:
      - 'scripts/getBuildConanCachesPackageInfo.py'
      - 'scripts/natron_conan_env.py'
      - '.github/workflows/build_conan_caches.yml'
      - 'recipes/natron/all/conanfile.py'
      - 'modules/conan-center-index'

  schedule:
    - cron:  '11 6 * * *'

jobs:
  get_packages_to_build:

    name: Get Packages to Build
    runs-on: ubuntu-latest

    outputs:
      package_info: ${{ steps.gen_package_info.outputs.package_info }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generating Package Info
        id: gen_package_info
        run: |
          python scripts/getBuildConanCachesPackageInfo.py >> $GITHUB_OUTPUT

  build_package_matrix:
    strategy:
      fail-fast: false
      matrix:
        os:
          - runs_on: ubuntu-latest
            conan_profile: linux_default
          - runs_on: windows-latest
            conan_profile: msvc_profile
            conan_build_workspace: 'D:/cbw'
          - runs_on: macos-13
            conan_profile: macos_default
          - runs_on: macos-14
            conan_profile: macos_arm_default
        packages: ${{ fromJson(needs.get_packages_to_build.outputs.package_info) }}

    name: Build ${{ matrix.os.conan_profile }} - ${{ matrix.packages.name }}
    runs-on: ${{ matrix.os.runs_on }}
    continue-on-error: true
    needs: [get_packages_to_build]

    env:
      CONAN_BUILD_WORKSPACE: ${{ matrix.os.conan_build_workspace }}
      CONAN_CACHE_FILENAME: conan-cache-save_${{ matrix.packages.name }}_${{ matrix.os.conan_profile }}.tgz

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Setup Conan environment
        uses: ./.github/workflows/conan_setup_action
        with:
          conan_profile: ${{ matrix.os.conan_profile }}

      - name: Install dependencies
        run: |
          conan install -pr:a ${{ matrix.os.conan_profile }} --build=missing --version=${{ matrix.packages.version }} ${{ matrix.packages.extra_options }} ${{ matrix.packages.path }}

      - name: Remove unnecessary files from cache before building
        run: |
          conan cache clean '*'

      - name: Build package
        run: |
          conan install -pr:a ${{ matrix.os.conan_profile }} --build=missing --requires=${{ matrix.packages.name }}/${{ matrix.packages.version }} ${{ matrix.packages.extra_options }}

      - name: Remove unnecessary files from cache
        run: |
          conan cache clean '*'

      - name: Remove msys2 package from cache
        if: runner.os == 'Windows'
        run: |
          conan remove -c "msys2/*"

      - name: Save cache to file
        run: |
          conan cache save --file=${{ env.CONAN_CACHE_FILENAME }} '*:*'

      - name: Upload cache
        uses: actions/upload-artifact@v4.3.1
        with:
          name:  ${{ env.CONAN_CACHE_FILENAME }}
          path:  ${{ env.CONAN_CACHE_FILENAME }}

  merge_packages_matrix:
    strategy:
      fail-fast: false
      matrix:
        os:
          - runs_on: ubuntu-latest
            conan_profile: linux_default
          - runs_on: windows-latest
            conan_profile: msvc_profile
            conan_build_workspace: 'D:/cbw'
          - runs_on: macos-13
            conan_profile: macos_default
          - runs_on: macos-14
            conan_profile: macos_arm_default

    name: Merge ${{ matrix.os.conan_profile }} packages
    runs-on: ${{ matrix.os.runs_on }}
    needs: [build_package_matrix]

    env:
      CONAN_BUILD_WORKSPACE: ${{ matrix.os.conan_build_workspace }}
      CONAN_CACHE_FILENAME: conan-cache-save_${{ matrix.os.conan_profile }}.tgz

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Setup Conan environment
        uses: ./.github/workflows/conan_setup_action
        with:
          conan_profile: ${{ matrix.os.conan_profile }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: conan-cache-save_*_${{ matrix.os.conan_profile }}.tgz
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Add each package to cache
        run: |
          python3 scripts/restoreConanCacheSaves.py --remove artifacts

      - name: Remove unnecessary files from cache
        run: |
          conan cache clean '*'

      - name: Build or Install Natron Installer dependencies
        run: |
          conan install -pr:a ${{ matrix.os.conan_profile }} --update --build=missing  --requires 'natron_installer/conan_build' --build '~natron_installer/conan_build' --lockfile-partial --lockfile-out ${{ matrix.os.conan_profile }}-conan.lock

      - name: Dump New Lockfile
        run: |
          cat ${{ matrix.os.conan_profile }}-conan.lock

      - name: Save cache to file
        run: |
          conan cache save --file=${{ env.CONAN_CACHE_FILENAME }} '*:*'

      - name: Upload cache
        uses: actions/upload-artifact@v4.3.1
        with:
          name:  ${{ env.CONAN_CACHE_FILENAME }}
          path:  ${{ env.CONAN_CACHE_FILENAME }}
